export { cn } from "./utils";
export { getMockResults, type AggregatedResult } from "./dataService";
export {
  calculateCRS5Score,
  getReligiosityLevel,
  RELIGIOSITY_LABELS,
  calculateGeneralAIScore,
  calculateSpiritualAIScore,
  calculateSpiritualResistanceIndex,
  getResistanceLevel,
  RESISTANCE_LABELS,
  calculateAIAdoptionScore,
  getAIAdoptionLevel,
  AI_ADOPTION_LABELS,
  getSpiritualAIProfile,
  PROFILE_DATA,
  getPercentileComparison,
  generateInsights,
  type ReligiosityLevel,
  type AIAdoptionLevel,
  type ResistanceLevel,
  type TheologicalOrientation,
  type SpiritualAIProfile,
  type PersonalizedInsight,
} from "./scoring";
